# Example 4: Find the 3 closest features to feature `my:C', where
# computations are based on `my:hasExactGeometry'.

prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix geof: <http://www.opengis.net/def/geosparql/function>
prefix my: <http://example.org/ApplicationSchema#>
prefix uom: <http://www.opengis.net/def/uom/OGC/1.0/>
select ?f {
  my:C my:hasExactGeometry ?cGeom .
  ?cGeom geo:asWKT ?cWKT .
  ?f my:hasExactGeometry ?fGeom .
  ?fGeom geo:asWKT ?fWKT .
  filter (?fGeom != ?cGeom)
}
order by asc(geof:distance(?cWKT, ?fWKT, uom:metre))
limit 3
